version: '3.8'
services:
  app:
    build: .
    ports:
      - "${REPORT_SERVER_PORT}:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${REPORT_DB_PORT}/${REPORT_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${REPORT_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${REPORT_DB_PASSWORD}

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${REPORT_DB_USERNAME}
      - POSTGRES_PASSWORD=${REPORT_DB_PASSWORD}
      - POSTGRES_DB=${REPORT_DB_NAME}
    ports:
      - "${REPORT_DB_PORT}:5432"